name: Deploy documentation

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.?[0-9]*.?[0-9]*'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Build
      run: ./cicd/ubuntu.sh docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        force_orphan: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doc/out/html
